name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update -y
        sudo apt install wine-stable wine32 -y
        yarn --frozen-lockfile
      
    - name: Build packages and upload to Github releases
      run: yarn dist:publish
